---
title: 'Inaugural Post'
author: Cory Sauve
date: '2019-08-24'
slug: welcome-to-my-website
categories: []
tags: []
subtitle: ''
summary: 'Welcome to my site!'
authors: []
lastmod: '2019-08-24T20:16:50-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Thanks for checking out my site! I've wanted to improve my online precence for awhile now and   
have finally sat down and made a website.  I created and am maintaining this site via the R `blogdown` package and Hugo.  You can check out my GitHub repo if your interested in the use   
of `blogdown` to make static websites. 

My goal for this site is to accomplish two things: first to serve as a medium for which I can start bloggging my programming endevours relating to my work and random things that interest me, as well as to serve as a digitial resume and portfolio.  I'm hoping to have a new post up every week.  Now that it's football season again, expect some fantasy football analysis in R and Python (yes, this is what I do on the weekends for fun).  

Anyway, thanks for visiting my site! 

-- Cory 